[2024-05-24T09:08:09.604+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T09:08:09.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-05-24T09:08:08.259964+00:00 [queued]>
[2024-05-24T09:08:09.626+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-05-24T09:08:08.259964+00:00 [queued]>
[2024-05-24T09:08:09.626+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T09:08:09.637+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-05-24 09:08:08.259964+00:00
[2024-05-24T09:08:09.641+0000] {standard_task_runner.py:63} INFO - Started process 83 to run task
[2024-05-24T09:08:09.645+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-05-24T09:08:08.259964+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp0l7n9ow6']
[2024-05-24T09:08:09.647+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask reddit_extraction
[2024-05-24T09:08:09.690+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-05-24T09:08:08.259964+00:00 [running]> on host f174faf60ef4
[2024-05-24T09:08:09.764+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='OlivierAssiene' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T09:08:08.259964+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T09:08:08.259964+00:00'
[2024-05-24T09:08:09.764+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T09:08:09.776+0000] {logging_mixin.py:188} INFO - Connected successfully to Reddit!
[2024-05-24T09:08:10.663+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T09:08:10.663+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 16, in reddit_pipeline
    load_data_to_csv(post_df, file_path)
  File "/opt/airflow/etls/reddit_etl.py", line 40, in load_data_to_csv
    data.to_csv(path, index=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/output/reddit_20240524090809.csv'
[2024-05-24T09:08:10.673+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-05-24T09:08:08.259964+00:00, execution_date=20240524T090808, start_date=20240524T090809, end_date=20240524T090810
[2024-05-24T09:08:10.684+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task reddit_extraction ([Errno 13] Permission denied: '/opt/airflow/data/output/reddit_20240524090809.csv'; 83)
[2024-05-24T09:08:10.705+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-24T09:08:10.718+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T09:08:10.721+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
